# Site settings
title: Ricky Holtz Portfolio
email: ricky.holtz@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
    just trying to make stuff
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rickydesign.me" # the base hostname & protocol for your site
twitter_username: ayyrickay
github_username:  ayyrickay

# Build settings
markdown: kramdown
